language: go
go: "1.11"

before_install:
- sudo curl -JL https://github.com/operator-framework/operator-sdk/releases/download/v0.8.0/operator-sdk-v0.8.0-x86_64-linux-gnu -o /usr/bin/operator-sdk
- sudo chmod +x /usr/bin/operator-sdk
- go get -v github.com/onsi/ginkgo/ginkgo
- export PATH=$PATH:$HOME/gopath/bin
install: true
script:
- make all test/unit
