apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-nmstate-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-nmstate-manager
  template:
    metadata:
      labels:
        name: kubernetes-nmstate-manager
    spec:
      serviceAccountName: kubernetes-nmstate-manager
      containers:
        - name: kubernetes-nmstate-manager
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - kubernetes-nmstate-manager
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubernetes-nmstate-manager"
